gz_ros_control:
  ros__parameters:
    hold_joints: true
    position_proportional_gain: 0.5

controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    joints:
      - joint2_to_joint1
      - joint3_to_joint2
      - joint4_to_joint3
      - joint5_to_joint4
      - joint6_to_joint5
      - joint6output_to_joint6
    command_interfaces:
      - position
    state_interfaces:
      - position
    allow_partial_joints_goal: false
    open_loop_control: false
    allow_integration_in_goal_trajectories: true
    allow_nonzero_velocity_at_trajectory_end: true

gripper_trajectory_controller:
  ros__parameters:
    joints:
      - gripper_controller
    command_interfaces:
      - position
    state_interfaces:
      - position
    allow_partial_joints_goal: false
